project:
  type: website
  output-dir: docs
  
website:
  title: "PSMVC-2"
  navbar:
    left:
      - about.qmd

format:
  html:
    theme:
      - Cerulean
    toc: true

editor: visual

resources:
  - Literature/*.pdf
  - Presentations/*.pdf
  - Presentations/*.pptx
  - Demo\ Experiment/*.osexp
  